version: 2
multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Europe/Madrid"
    target-branch: "develop"
    open-pull-requests-limit: 1
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    multi-ecosystem-group: "all-dependencies"
    patterns:
      - "*"
    cooldown:
      default-days: 7
      semver-major-days: 30
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    rebase-strategy: "disabled"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "all-dependencies"
    patterns:
      - "*"
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    rebase-strategy: "disabled"
    labels:
      - "dependencies"
