// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsClubEventManager.Infrastructure.Persistence;

#nullable disable

namespace SportsClubEventManager.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260623155030_AddDevelopmentSeedData")]
    partial class AddDevelopmentSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsClubEventManager.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Social shooting competition for 9mm pistol enthusiasts. Open to all categories.",
                            Location = "Zaragoza - CTZ",
                            MaxCapacity = 20,
                            Title = "Pistola 9mm - Social"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 3, 20, 9, 30, 0, 0, DateTimeKind.Utc),
                            Description = "BR50 rifle trophy competition. Precision benchrest shooting at 50 meters.",
                            Location = "Teruel - CT Aguanaces",
                            MaxCapacity = 15,
                            Title = "Carabina BR50 - Trofeo"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 6, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Regional championship for air pistol. Part of the Aragon Cup series.",
                            Location = "Huesca - RTAA",
                            MaxCapacity = 15,
                            Title = "Aire Comprimido Pistola - Copa Aragón"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Provincial championship for standard pistol category. Includes precision and rapid fire stages.",
                            Location = "Madrid - RFEDETO",
                            MaxCapacity = 20,
                            Title = "Pistola Estándar - Campeonato Provincial"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 12, 10, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Friendly air rifle competition. Perfect for beginners and experienced shooters alike.",
                            Location = "Barcelona - CT Vallès",
                            MaxCapacity = 20,
                            Title = "Aire Comprimido Carabina - Social"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 18, 11, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Speed shooting competition. Fast-paced action with precision requirements.",
                            Location = "Valencia - CTW",
                            MaxCapacity = 30,
                            Title = "Pistola de Velocidad - Trofeo del Globo"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "3-position rifle championship. Prone, standing, and kneeling positions at 50m.",
                            Location = "Zaragoza - CTZ",
                            MaxCapacity = 15,
                            Title = "Carabina 3x20 - Campeonato Provincial"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 7, 30, 8, 30, 0, 0, DateTimeKind.Utc),
                            Description = "50 meter precision pistol competition. Olympic discipline, high precision required.",
                            Location = "Teruel - CT Aguanaces",
                            MaxCapacity = 40,
                            Title = "Pistola 50m - Copa Aragón"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 9, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clay pigeon shooting competition. Trap discipline with variable trajectories.",
                            Location = "Huesca - RTAA",
                            MaxCapacity = 30,
                            Title = "Trap - Trofeo"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateTime(2026, 12, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Universal trench shooting event. End-of-season friendly competition.",
                            Location = "Madrid - RFEDETO",
                            MaxCapacity = 20,
                            Title = "Foso Universal - Social"
                        });
                });

            modelBuilder.Entity("SportsClubEventManager.Domain.Entities.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("Registrations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 2, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RegistrationDate = new DateTime(2026, 2, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("20000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 2, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RegistrationDate = new DateTime(2026, 2, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("30000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 5, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RegistrationDate = new DateTime(2026, 5, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("30000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 5, 15, 11, 20, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RegistrationDate = new DateTime(2026, 5, 15, 11, 20, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("30000003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 5, 20, 16, 45, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RegistrationDate = new DateTime(2026, 5, 20, 16, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("40000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 5, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RegistrationDate = new DateTime(2026, 5, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("40000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 5, 16, 9, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RegistrationDate = new DateTime(2026, 5, 16, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("40000003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 5, 17, 10, 15, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RegistrationDate = new DateTime(2026, 5, 17, 10, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("40000004-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 5, 18, 11, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RegistrationDate = new DateTime(2026, 5, 18, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("40000005-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 5, 19, 12, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RegistrationDate = new DateTime(2026, 5, 19, 12, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("40000006-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 5, 20, 13, 15, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RegistrationDate = new DateTime(2026, 5, 20, 13, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("10101010-1010-1010-1010-101010101010")
                        },
                        new
                        {
                            Id = new Guid("40000007-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 5, 21, 14, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RegistrationDate = new DateTime(2026, 5, 21, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Cancelled",
                            UpdatedAt = new DateTime(2026, 5, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("40000008-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 5, 22, 15, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RegistrationDate = new DateTime(2026, 5, 22, 15, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("40000009-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 5, 23, 16, 45, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RegistrationDate = new DateTime(2026, 5, 23, 16, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("40000010-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 5, 24, 17, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RegistrationDate = new DateTime(2026, 5, 24, 17, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("40000011-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 5, 25, 18, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RegistrationDate = new DateTime(2026, 5, 25, 18, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("50000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("50000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 2, 8, 15, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 8, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("50000003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 2, 8, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 8, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("50000004-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 2, 8, 45, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 8, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("50000005-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("50000006-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 6, 2, 9, 15, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 9, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("10101010-1010-1010-1010-101010101010")
                        },
                        new
                        {
                            Id = new Guid("50000007-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 6, 2, 9, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("50000008-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 6, 2, 9, 45, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 9, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("50000009-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 6, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("50000010-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 6, 2, 10, 15, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 10, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("50000011-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 6, 2, 10, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 10, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("50000012-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 6, 2, 10, 45, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 10, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("10101010-1010-1010-1010-101010101010")
                        },
                        new
                        {
                            Id = new Guid("50000013-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 6, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("50000014-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 6, 2, 11, 15, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 11, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("50000015-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 6, 2, 11, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 11, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("50000016-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTime(2026, 6, 2, 11, 45, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 11, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("50000017-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTime(2026, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("50000018-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTime(2026, 6, 2, 12, 15, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RegistrationDate = new DateTime(2026, 6, 2, 12, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("10101010-1010-1010-1010-101010101010")
                        },
                        new
                        {
                            Id = new Guid("60000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 6, 8, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("60000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 6, 8, 5, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 8, 5, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("60000003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 6, 8, 10, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 8, 10, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("60000004-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 6, 8, 15, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 8, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("60000005-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 6, 8, 20, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 8, 20, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("60000006-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 6, 6, 8, 25, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 8, 25, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("10101010-1010-1010-1010-101010101010")
                        },
                        new
                        {
                            Id = new Guid("60000007-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 6, 6, 8, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 8, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("60000008-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 6, 6, 8, 35, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 8, 35, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("60000009-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 6, 6, 8, 40, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 8, 40, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("60000010-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 6, 6, 8, 45, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 8, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("60000011-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 6, 6, 8, 50, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 8, 50, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("60000012-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 6, 6, 8, 55, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 8, 55, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("10101010-1010-1010-1010-101010101010")
                        },
                        new
                        {
                            Id = new Guid("60000013-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 6, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("60000014-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 6, 6, 9, 5, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 9, 5, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("60000015-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 6, 6, 9, 10, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 9, 10, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("60000016-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTime(2026, 6, 6, 9, 15, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 9, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("60000017-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTime(2026, 6, 6, 9, 20, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 9, 20, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("60000018-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTime(2026, 6, 6, 9, 25, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 9, 25, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("10101010-1010-1010-1010-101010101010")
                        },
                        new
                        {
                            Id = new Guid("60000019-0000-0000-0000-000000000019"),
                            CreatedAt = new DateTime(2026, 6, 6, 9, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("60000020-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTime(2026, 6, 6, 9, 35, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 9, 35, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("60000021-0000-0000-0000-000000000021"),
                            CreatedAt = new DateTime(2026, 6, 6, 9, 40, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 9, 40, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("60000022-0000-0000-0000-000000000022"),
                            CreatedAt = new DateTime(2026, 6, 6, 9, 45, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 9, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("60000023-0000-0000-0000-000000000023"),
                            CreatedAt = new DateTime(2026, 6, 6, 9, 50, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 9, 50, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("60000024-0000-0000-0000-000000000024"),
                            CreatedAt = new DateTime(2026, 6, 6, 9, 55, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 9, 55, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("10101010-1010-1010-1010-101010101010")
                        },
                        new
                        {
                            Id = new Guid("60000025-0000-0000-0000-000000000025"),
                            CreatedAt = new DateTime(2026, 6, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("60000026-0000-0000-0000-000000000026"),
                            CreatedAt = new DateTime(2026, 6, 6, 10, 5, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 10, 5, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("60000027-0000-0000-0000-000000000027"),
                            CreatedAt = new DateTime(2026, 6, 6, 10, 10, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 10, 10, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("60000028-0000-0000-0000-000000000028"),
                            CreatedAt = new DateTime(2026, 6, 6, 10, 15, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 10, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("60000029-0000-0000-0000-000000000029"),
                            CreatedAt = new DateTime(2026, 6, 6, 10, 20, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 10, 20, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("60000030-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTime(2026, 6, 6, 10, 25, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("66666666-6666-6666-6666-666666666666"),
                            RegistrationDate = new DateTime(2026, 6, 6, 10, 25, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("10101010-1010-1010-1010-101010101010")
                        },
                        new
                        {
                            Id = new Guid("70000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("77777777-7777-7777-7777-777777777777"),
                            RegistrationDate = new DateTime(2026, 6, 11, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("70000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 11, 9, 15, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("77777777-7777-7777-7777-777777777777"),
                            RegistrationDate = new DateTime(2026, 6, 11, 9, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("70000003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 11, 9, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("77777777-7777-7777-7777-777777777777"),
                            RegistrationDate = new DateTime(2026, 6, 11, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("70000004-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 11, 9, 45, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("77777777-7777-7777-7777-777777777777"),
                            RegistrationDate = new DateTime(2026, 6, 11, 9, 45, 0, 0, DateTimeKind.Utc),
                            Status = "Cancelled",
                            UpdatedAt = new DateTime(2026, 6, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("70000005-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("77777777-7777-7777-7777-777777777777"),
                            RegistrationDate = new DateTime(2026, 6, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("70000006-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 6, 11, 10, 15, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("77777777-7777-7777-7777-777777777777"),
                            RegistrationDate = new DateTime(2026, 6, 11, 10, 15, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("10101010-1010-1010-1010-101010101010")
                        },
                        new
                        {
                            Id = new Guid("80000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 6, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("88888888-8888-8888-8888-888888888888"),
                            RegistrationDate = new DateTime(2026, 6, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("80000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 6, 16, 8, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("88888888-8888-8888-8888-888888888888"),
                            RegistrationDate = new DateTime(2026, 6, 16, 8, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("80000003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 6, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("88888888-8888-8888-8888-888888888888"),
                            RegistrationDate = new DateTime(2026, 6, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("80000004-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 6, 16, 9, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("88888888-8888-8888-8888-888888888888"),
                            RegistrationDate = new DateTime(2026, 6, 16, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Cancelled",
                            UpdatedAt = new DateTime(2026, 6, 17, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("80000005-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 6, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("88888888-8888-8888-8888-888888888888"),
                            RegistrationDate = new DateTime(2026, 6, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff")
                        },
                        new
                        {
                            Id = new Guid("80000006-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 6, 16, 10, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("88888888-8888-8888-8888-888888888888"),
                            RegistrationDate = new DateTime(2026, 6, 16, 10, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("10101010-1010-1010-1010-101010101010")
                        },
                        new
                        {
                            Id = new Guid("80000007-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 6, 16, 11, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("88888888-8888-8888-8888-888888888888"),
                            RegistrationDate = new DateTime(2026, 6, 16, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("80000008-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 6, 16, 11, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("88888888-8888-8888-8888-888888888888"),
                            RegistrationDate = new DateTime(2026, 6, 16, 11, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("80000009-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 6, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("88888888-8888-8888-8888-888888888888"),
                            RegistrationDate = new DateTime(2026, 6, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Cancelled",
                            UpdatedAt = new DateTime(2026, 6, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("80000010-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 6, 16, 12, 30, 0, 0, DateTimeKind.Utc),
                            EventId = new Guid("88888888-8888-8888-8888-888888888888"),
                            RegistrationDate = new DateTime(2026, 6, 16, 12, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Registered",
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        });
                });

            modelBuilder.Entity("SportsClubEventManager.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicenseCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carmen.garcia@example.com",
                            Gender = "Female",
                            LicenseCategory = "A",
                            LicenseNumber = "ESP-2026-001",
                            Name = "Carmen García López"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "javier.martinez@example.com",
                            Gender = "Male",
                            LicenseCategory = "S",
                            LicenseNumber = "ESP-2026-002",
                            Name = "Javier Martínez Ruiz"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ana.fernandez@example.com",
                            Gender = "Female",
                            LicenseCategory = "A",
                            LicenseNumber = "ESP-2026-003",
                            Name = "Ana Fernández Pérez"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreatedAt = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "miguel.sanchez@example.com",
                            Gender = "Male",
                            Name = "Miguel Sánchez Torres"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "laura.rodriguez@example.com",
                            Gender = "Female",
                            LicenseCategory = "S",
                            LicenseNumber = "ESP-2026-004",
                            Name = "Laura Rodríguez Gómez"
                        },
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101010"),
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carlos.jimenez@example.com",
                            Gender = "Male",
                            LicenseCategory = "A",
                            LicenseNumber = "ESP-2026-005",
                            Name = "Carlos Jiménez Moreno"
                        });
                });

            modelBuilder.Entity("SportsClubEventManager.Domain.Entities.Registration", b =>
                {
                    b.HasOne("SportsClubEventManager.Domain.Entities.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsClubEventManager.Domain.Entities.User", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportsClubEventManager.Domain.Entities.Event", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("SportsClubEventManager.Domain.Entities.User", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
